module.exports = {
    "light": {
        // 背景色
        "background-color": "#ffffff",
        "first-bg-color": "#f6f6f6",
        "second-bg-color": "#eaeaea",
        "third-bg-color": "#e1e1e1",
        "fouth-bg-color": "#dedede",
        // 字体颜色
        "font-color": "#333333",
        "first-color": "#525252",
        "second-color": "#747474",
        "third-color": "#979797",
        "fouth-color": "#bababa",
        // 边框颜色
        "border-color": "#dcdcdc",
        "first-border-color": "#cccccc",
        "second-border-color": "#efefef",
        // 面板颜色
        "panel-color": "#f1f1f1",
        // 面板悬停色
        "panel-hover-color": "#dcdcdc",
        // 面板激活色
        "panel-active-color": "#aaaaaa",
        // 交互元素色
        "tool-color": "#666666",
        "tool-first-color": "#777777",
        "tool-second-color": "#888888",
        // 只读色
        "readonly-color": "#666666",
        // 禁用色
        "disabled-color": "#aaaaaa",
        // 悬停色
        "hover-color": "#434343",
        // 激活色
        "active-color": "#434343",
        // 阴影色
        "shadow-color": "#434343"
    },
    "dark": {
        // 背景色
        "background-color": "#1d1f21",
        "first-bg-color": "#2e3032",
        "second-bg-color": "#37383a",
        "third-bg-color": "#434547",
        "fouth-bg-color": "#505253",
        // 字体颜色
        "font-color": "#aaaaaa",
        "first-color": "#949494",
        "second-color": "#808080",
        "third-color": "#737373",
        "fouth-color": "#676767",
        // 边框颜色
        "border-color": "#5d5f60",
        "first-border-color": "#3c3f41",
        "second-border-color": "#4b4d4f",
        // 面板颜色
        "panel-color": "#3c3f41",
        // 面板悬停色
        "panel-hover-color": "#5d5f60",
        // 面板激活色
        "panel-active-color": "#1d1f21",
        // 交互元素色
        "tool-color": "#888888",
        "tool-first-color": "#999999",
        "tool-second-color": "#aaaaaa",
        // 只读色
        "readonly-color": "#888888",
        // 禁用色
        "disabled-color": "#5d5f60",
        // 悬停色
        "hover-color": "#999999",
        // 激活色
        "active-color": "#999999",
        // 阴影色
        "shadow-color": "#999999"
    }
}
